### ISSUE TITLE
 error: ‘REG_RIP’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by skxo** [trzy/PeepingTomasulo#1]
Hi,

just a remark, I have add one line into peepingtom.c to avoid compilation error:

#define _GNU_SOURCE 1

then I can compile 
gcc -o peepingtom peepingtom.c

Thanks for your file!
Regards
sk

**Comment by trzy** [comment]
Thanks!  I think "#define __USE_GNU" might be a more generic solution 
and I've committed that update to the repo.  If you use __USE_GNU rather 
than _GNU_SOURCE, does it still work for you?  I also compile with 
-std=gnu99 and added that to the comment at the top.

**Comment by trzy** [comment]
Should be fixed.
